; Auto-generated. Do not edit!


(cl:in-package action-msg)


;//! \htmlinclude addintsResult.msg.html

(cl:defclass <addintsResult> (roslisp-msg-protocol:ros-message)
  ((result
    :reader result
    :initarg :result
    :type cl:integer
    :initform 0))
)

(cl:defclass addintsResult (<addintsResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <addintsResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'addintsResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name action-msg:<addintsResult> is deprecated: use action-msg:addintsResult instead.")))

(cl:ensure-generic-function 'result-val :lambda-list '(m))
(cl:defmethod result-val ((m <addintsResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader action-msg:result-val is deprecated.  Use action-msg:result instead.")
  (result m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <addintsResult>) ostream)
  "Serializes a message object of type '<addintsResult>"
  (cl:let* ((signed (cl:slot-value msg 'result)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <addintsResult>) istream)
  "Deserializes a message object of type '<addintsResult>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'result) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<addintsResult>)))
  "Returns string type for a message object of type '<addintsResult>"
  "action/addintsResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'addintsResult)))
  "Returns string type for a message object of type 'addintsResult"
  "action/addintsResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<addintsResult>)))
  "Returns md5sum for a message object of type '<addintsResult>"
  "034a8e20d6a306665e3a5b340fab3f09")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'addintsResult)))
  "Returns md5sum for a message object of type 'addintsResult"
  "034a8e20d6a306665e3a5b340fab3f09")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<addintsResult>)))
  "Returns full string definition for message of type '<addintsResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# 最终返回变量~%int32 result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'addintsResult)))
  "Returns full string definition for message of type 'addintsResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# 最终返回变量~%int32 result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <addintsResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <addintsResult>))
  "Converts a ROS message object to a list"
  (cl:list 'addintsResult
    (cl:cons ':result (result msg))
))
