; Auto-generated. Do not edit!


(cl:in-package action-msg)


;//! \htmlinclude addintsGoal.msg.html

(cl:defclass <addintsGoal> (roslisp-msg-protocol:ros-message)
  ((num
    :reader num
    :initarg :num
    :type cl:integer
    :initform 0))
)

(cl:defclass addintsGoal (<addintsGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <addintsGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'addintsGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name action-msg:<addintsGoal> is deprecated: use action-msg:addintsGoal instead.")))

(cl:ensure-generic-function 'num-val :lambda-list '(m))
(cl:defmethod num-val ((m <addintsGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader action-msg:num-val is deprecated.  Use action-msg:num instead.")
  (num m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <addintsGoal>) ostream)
  "Serializes a message object of type '<addintsGoal>"
  (cl:let* ((signed (cl:slot-value msg 'num)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <addintsGoal>) istream)
  "Deserializes a message object of type '<addintsGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'num) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<addintsGoal>)))
  "Returns string type for a message object of type '<addintsGoal>"
  "action/addintsGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'addintsGoal)))
  "Returns string type for a message object of type 'addintsGoal"
  "action/addintsGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<addintsGoal>)))
  "Returns md5sum for a message object of type '<addintsGoal>"
  "54b3c80efd6fae6e6ffff8a4b9facd69")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'addintsGoal)))
  "Returns md5sum for a message object of type 'addintsGoal"
  "54b3c80efd6fae6e6ffff8a4b9facd69")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<addintsGoal>)))
  "Returns full string definition for message of type '<addintsGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# 目标数据变量~%int32 num~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'addintsGoal)))
  "Returns full string definition for message of type 'addintsGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# 目标数据变量~%int32 num~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <addintsGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <addintsGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'addintsGoal
    (cl:cons ':num (num msg))
))
