<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="my_car">
    <xacro:property name="support_radius" value="0.01"/>
    <xacro:property name="support_length" value="0.15"/>
    <xacro:property name="laser_radius" value="0.03"/>
    <xacro:property name="laser_length" value="0.05"/>
    <xacro:property name="joint_support_x" value="0"/>
    <xacro:property name="joint_support_y" value="0"/>
    <xacro:property name="joint_support_z" value="${(baselink_length + support_length) / 2}"/>
    <xacro:property name="joint_laser_x" value="0"/>
    <xacro:property name="joint_laser_y" value="0"/>
    <xacro:property name="joint_laser_z" value="${(support_length + laser_length) / 2}"/>

    <link name="support">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${support_radius}" length="${support_length}"/>
            </geometry>
            <material name="yellow">
                <color rgba="0.8 0.5 0.0 0.6"/>
            </material>
        </visual>
    </link>

    <joint name="support2baselink" type="fixed">
        <origin xyz="${joint_support_x} ${joint_support_y} ${joint_support_z}" rpy="0.0 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="support"/>
    </joint>

    <link name="laser">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${laser_radius}" length="${laser_length}"/>
            </geometry>
            <material name="black">
                <color rgba="0.0 0.0 0.0 0.8"/>
            </material>
        </visual>
    </link>

    <joint name="laser2support" type="fixed">
        <origin xyz="${joint_laser_x} ${joint_laser_y} ${joint_laser_z}" rpy="0.0 0.0 0.0"/>
        <parent link="support"/>
        <child link="laser"/>
    </joint>
</robot>