// Generated by gencpp from file action/addintsFeedback.msg
// DO NOT EDIT!


#ifndef ACTION_MESSAGE_ADDINTSFEEDBACK_H
#define ACTION_MESSAGE_ADDINTSFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace action
{
template <class ContainerAllocator>
struct addintsFeedback_
{
  typedef addintsFeedback_<ContainerAllocator> Type;

  addintsFeedback_()
    : percent(0.0)  {
    }
  addintsFeedback_(const ContainerAllocator& _alloc)
    : percent(0.0)  {
  (void)_alloc;
    }



   typedef double _percent_type;
  _percent_type percent;





  typedef boost::shared_ptr< ::action::addintsFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::action::addintsFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct addintsFeedback_

typedef ::action::addintsFeedback_<std::allocator<void> > addintsFeedback;

typedef boost::shared_ptr< ::action::addintsFeedback > addintsFeedbackPtr;
typedef boost::shared_ptr< ::action::addintsFeedback const> addintsFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::action::addintsFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::action::addintsFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::action::addintsFeedback_<ContainerAllocator1> & lhs, const ::action::addintsFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.percent == rhs.percent;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::action::addintsFeedback_<ContainerAllocator1> & lhs, const ::action::addintsFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace action

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::action::addintsFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::action::addintsFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::action::addintsFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::action::addintsFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::action::addintsFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::action::addintsFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::action::addintsFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d6e607cac4f6b2d41392a1a3b72e4390";
  }

  static const char* value(const ::action::addintsFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd6e607cac4f6b2d4ULL;
  static const uint64_t static_value2 = 0x1392a1a3b72e4390ULL;
};

template<class ContainerAllocator>
struct DataType< ::action::addintsFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "action/addintsFeedback";
  }

  static const char* value(const ::action::addintsFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::action::addintsFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# 连续返回变量\n"
"float64 percent\n"
;
  }

  static const char* value(const ::action::addintsFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::action::addintsFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.percent);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct addintsFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::action::addintsFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::action::addintsFeedback_<ContainerAllocator>& v)
  {
    s << indent << "percent: ";
    Printer<double>::stream(s, indent + "  ", v.percent);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACTION_MESSAGE_ADDINTSFEEDBACK_H
